name: "citycat actions"

on:
  push:
    branches: 'main'

jobs:
  build-and-run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.11

      - name: build cpp
        working-directory: ./cpp
        run: nix-build

      - name: build hs
        working-directory: ./hs
        run: nix-build

